name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'performance'
  - title: '🔧 Refactoring'
    labels:
      - 'refactor'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'documentation'
      - 'refactor'
      - 'performance'
      - 'test'
      - 'testing'
  default: patch

template: |
  ## CSV2JSON Converter v$RESOLVED_VERSION

  $CHANGES

  **Full Changelog**: https://github.com/username/csv2json/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
